### ISSUE TITLE
Requirements in setup.py

### ISSUE THREAD

**Issue by baudren** [MycroftAI/adapt#10]
Thank you for sharing such a nice tool!

Small issue, when installing the code with `python setup.py install`, not all the requirements come along: `setup.py` does not refer to the `requirements.txt`. It would be nicer if it was the case, for packaging.

**Comment by clusterfudge** [comment]
Agreed. I've done this in previous projects, but it's a naive reading of the requirements.txt file into the install_requires array. Is there something else that's considered a best practice?

**Comment by clusterfudge** [comment]
I'm going to update just the setup file now, awaiting your response.

**Comment by baudren** [comment]
The other best practice bit that was missing was from the example codes (not respecting the PEP8 coding standards, whereas the rest of the code seems clean enough). It would be nice to put them in a nicer form, since for many people it will be the first contact with the codebase.

**Comment by the-kid89** [comment]
On the note of making it a little easier to get in. I made a pull request to have test-requirements.txt pull from requirements.txt.

**Comment by clusterfudge** [comment]
Ok, nobody actually answered my question here. I've added the correct dependencies/versions to the setup file, and am going to close this.
