### ISSUE TITLE
Confusing examples: MultiIntent* examples define unused Parser and EntityTagger

### ISSUE THREAD

**Issue by PLNech** [MycroftAI/adapt#109]
# Problem

See the following excerpts of `multi_intent_parser.py` and `multi_domain_intent_parser.py`:

https://github.com/MycroftAI/adapt/blob/7c1e444cfbe1581ff97d4ef80752f8257a95f64c/examples/multi_intent_parser.py#L20-L25

https://github.com/MycroftAI/adapt/blob/7c1e444cfbe1581ff97d4ef80752f8257a95f64c/examples/multi_domain_intent_parser.py#L20-L25
 

In both cases, an `EnglishTokenizer` is imported, then used to create an `EntityTagger` and a `Parser`. But these two objects are not passed to the `IntentDeterminationEngine`, which actually only accepts a `Tokenizer` and `Trie` and always recreates its `EntityTagger` and `Parser` internally.

https://github.com/MycroftAI/adapt/blob/7c1e444cfbe1581ff97d4ef80752f8257a95f64c/adapt/engine.py#L39-L53

This makes understanding the different components of the Mycroft architecture more complicated that it should be.

# Proposal

To clarify these examples, I believe they should only define objects that are useful to demonstrating what they achieve. Thus, I believe we should:

- Remove the `Parser` and `EntityTagger` defined in both classes, as they cannot be passed to the `IntentDeterminationEngine`'s constructor.
- Use the `Tokenizer` and `Trie` defined above to construct the `IntentDeterminationEngine`.

Alternatively, if there is a case for injecting an `EntityTagger` and a `Parser` when constructing the Engine, I believe that class should be refactored to allow using the objects currently defined but unused in these examples.

# Discussion

Looking forward to hearing your take on this; should you agree with either proposal, happy to send a PR addressing this issue :smile:

**Comment by clusterfudge** [comment]
Hey @PLNech , thanks for your issue! You're right, it would appear that when I last updated the examples (around the same time much of the logic was encapsulated in `IntentDeterminationEngine`), I forgot to remove these instantiations from the class. You can see in [this change](https://github.com/MycroftAI/adapt/commit/b1a51a4bde21a6dcff1e6616f016f352dfbf9921#diff-086b31b47dfa8df3a9778c90547a3595) where I updated the simpler samples correctly, but missed the multi-intent examples.I'll go back and clean those up, and tag you in the PR. Thanks again!

**Comment by forslund** [comment]
Fix merged in #110. Closing
