### ISSUE TITLE
Entity matching more than it should

### ISSUE THREAD

**Issue by aussieW** [MycroftAI/adapt#116]
I am experiencing a problem with using regex. I have the following phrase defined in regex/en-us/City.rx
```
(for|at|in|on) (?P<city_name>.+)
```
but only when "on Tokyo" is spoken does it return "Tokyo". For the others it returns "for Tokyo", "at Tokyo" or "in Tokyo".

I have seen the problem on rpi3 running on both picroft and Mark 1 images.

I have a cut down version of my code at https://github.com/aussieW/regexProblem which demonstrates the problem.

**Comment by clusterfudge** [comment]
Sorry for the delayed response here! We've been working a bunch recently, and I believe your issues _may_ have been addressed by #137 . I don't have a good setup for installing your example to test (but thank you for crafting it!), but perhaps @forslund does?

In the mean time, I'm going to mark this as "close on 9/17" in the interest of wrapping up our 1.0.0 version. It's been a few years, so I'm not expecting a response, but if you do, I'll be here!
