### ISSUE TITLE
Adapt react-native

### ISSUE THREAD

**Issue by waseemAnsari11011** [MycroftAI/adapt#121]
How to use adapt speech-to-intent library in my react-native application????

**Comment by clusterfudge** [comment]
Hey @waseemAnsari11011 , thanks for your interest in Adapt!

Adapt is a python library, best suited for server-side or embedded environments, and there are currently no bindings for mobile-native languages. One option would be to have a server side component that runs adapt (among other things, as it is a small piece of the puzzle!), and communicate over the network. 

A quick google search doesn't yield any obvious (to me) results for what you're looking for, but you're welcome to continue searching that way as well.

**Comment by clusterfudge** [comment]
Closing as there hasn't been any further response.
