### ISSUE TITLE
Add license and test files to PyPI packages

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/adapt#124]
We've been slowly making Mycroft PyPI packages more consistent. 

Part of this has been including the LICENSE file in all distributions, and test directories in source distributions.

**Comment by forslund** [comment]
License file has been added will need to look at the tests some more.

**Comment by krisgesling** [comment]
looks like LICENSE.md is spelled incorrectly in the manifest

Can fix this to test the auto publishing PR :)
