### ISSUE TITLE
DomainIntentDeterminationEngine

### ISSUE THREAD

**Issue by clusterfudge** [MycroftAI/adapt#15]
An alternate implementation (or perhaps just an extension of IntentDeterminationEngine) would allow for specifying a "domain" (reminders, music, etc) when registering vocabulary and intents. The parser would then create candidate parse results for each domain, and yield in order of confidence (like the current implementation). This will help alleviate some issues where entity matches are breaking up wildcard regex entities (mentioning a radio inside a sms message could break the message body).

**Comment by the-kid89** [comment]
That sounds interesting.

**Comment by clusterfudge** [comment]
I do! this problem (of multiple domains) can be boiled down to [this interview question](https://www.careercup.com/question?id=9655082) that I've given and received many a time over the last 4 years.

DIDE == DomainIntentDeterminationEngine
IDE == IntentDeterminationEngine

Basically, the DIDE will have a collection of IDEs inside it, and on parse will invoke parse on each internal IDE, then march the results our of each generator in order (by highest parse result confidence).

Make sense?

**Comment by the-kid89** [comment]
I sent in a pull request with what I have right now. I wanted to check to see if this is along the lines of what you are looking for or not. If not we can update it so it is.

**Comment by clusterfudge** [comment]
Merged
