### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by ivuk** [MycroftAI/adapt#2]
Is Python 3 compatibility planned at this time (or any, for that matter)? If so, do you want to keep the project both Python 2 and Python 3 compatible?

It's really easy to get the examples running on Python 3 currently, it just requires dropping the `wsgiref` in `requirements.txt` and swapping the `xrange` calls.

**Comment by crutchcorn** [comment]
This would be great! :+1:

**Comment by clusterfudge** [comment]
No arguments here! wsgiref keeps sneaking into my projects thanks to virtualenv (or something like that), so I have no objections there. The xrange calls are a little more annoying. Adapt relies heavily on generators for efficiency, and switching the 2.x calls back to range would negatively impact performance. 

I'd be happy to approve a PR that uses the appropriate range impl for the given python version!

Longer term, we're going to have to maintain backwards compatibility for 2.x for older, lower powered devices where a python3 interpreter may not be readily available. We're also regularly taking on some native dependencies in upstream projects that we haven't tested against 3.x (We like 2.7 and we cannot lie!), so I'm not going to commit to 3.x support in the greater Mycroft ecosystem at this time.

**Comment by ivuk** [comment]
Cool, I'll have a look how other people are doing the `xrange` thing.

The wsgiref could be solved by using [environment markers](https://www.python.org/dev/peps/pep-0496/) in `requirements.txt`, so that `pip` ignores the package if `python_version` does not match. Something like this:
```
argparse==1.2.1
pyee==0.1.0
wsgiref==0.1.2 ; python_version == '2.7'
```
The downside is that the `pip` version on i.e. Ubuntu 15.10 is a bit older, so it doesn't understand markers; once you create a virtualenv, before running `pip install -r requirements.txt`, one should do `pip install --upgrade pip`. If this limitation is acceptable, I could do a small fix so that `requirements.txt` works for both Python 2 and 3.

**Comment by clusterfudge** [comment]
I think removing wsgiref (as we don't currently have any dependencies on it) will be fine for the time being, just to keep things simple.

**Comment by ivuk** [comment]
Well, I guess that works even better. :)

As far as the `xrange` is concerned, either `six` of `future` packages could be used. I'm not really well-versed with either, and there are [some differences](http://python-future.org/faq.html#what-is-the-relationship-between-future-and-six) between those modules, but it seems to be a pretty simple fix.

The `future` [approach](http://python-future.org/compatible_idioms.html#xrange) would be something like:
```sh
$ pip install future
$ python
Python 2.7.10 (default, Oct 14 2015, 16:09:02) 
[GCC 5.2.1 20151010] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from past.builtins import xrange
>>> xrange(0,5)
xrange(5)
>>> 
```
In a Python 3 virtualenv:
```sh
$ pip install future
$ python
Python 3.4.3+ (default, Oct 14 2015, 16:03:50) 
[GCC 5.2.1 20151010] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from past.builtins import xrange
>>> xrange(0,5)
range(0, 5)
>>> 
```
Naturally, the `future` package would need to be added to `requirements.txt`.

I've hacked up this a minute ago (on Python 3), and the examples run without complaining about the `xrange` calls.

**Comment by clusterfudge** [comment]
Can you also confirm the unit tests run? They have slightly better coverage than the unit tests. I'll be working on adding circle or travis to the repo soon so that's taken care of for you

PYTHONPATH=. python run_tests.py

**Comment by ivuk** [comment]
With the aforementioned change in place, the tests pass on Python 2, but fail on Python 3. The reason is a bit different, though, since it's related to a couple of new things:

*  `'dict_keys' object is not subscriptable` which I strongly suspect can be fixed via the `future` package (or `six`, if that's preferred)
*  `except ValueError, e:` which is different in Python 3 and IIRC can just be rewritten as `except ValueError as e:` for both Python 2.7 and 3

I'll fix the first point via the `future` package, if you agree. The second one is a trivial fix.

Test output is:
```
$ PYTHONPATH=. python run_tests.py

Running tests...
----------------------------------------------------------------------
EE.E..EEEEE...........
======================================================================
ERROR [0.004s]: testConsistentExpandWithSameOverlapMultipleTimes (test.EntityExpanderTest.BronKerboschExpanderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dev/shm/adapt/test/EntityExpanderTest.py", line 59, in testConsistentExpandWithSameOverlapMultipleTimes
    parse_results = list(expander.expand(tags, clique_scoring_func=score_clique))
  File "/dev/shm/adapt/adapt/expander.py", line 160, in expand
    cliques = list(self._sub_expand(overlapping_spans))
  File "/dev/shm/adapt/adapt/expander.py", line 130, in _sub_expand
    for clique in get_cliques(entities.keys(), graph):
  File "/dev/shm/adapt/adapt/expander.py", line 47, in get_cliques
    for clique in bronk([], vertices, [], graph):
  File "/dev/shm/adapt/adapt/expander.py", line 35, in bronk
    for vertex in p[:]:
TypeError: 'dict_keys' object is not subscriptable

======================================================================
ERROR [0.000s]: testExpandWithRegexAndLiteralTokenMatch (test.EntityExpanderTest.BronKerboschExpanderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dev/shm/adapt/test/EntityExpanderTest.py", line 75, in testExpandWithRegexAndLiteralTokenMatch
    cliques = list(expander._sub_expand(tags))
  File "/dev/shm/adapt/adapt/expander.py", line 130, in _sub_expand
    for clique in get_cliques(entities.keys(), graph):
  File "/dev/shm/adapt/adapt/expander.py", line 47, in get_cliques
    for clique in bronk([], vertices, [], graph):
  File "/dev/shm/adapt/adapt/expander.py", line 35, in bronk
    for vertex in p[:]:
TypeError: 'dict_keys' object is not subscriptable

======================================================================
ERROR [0.001s]: testExpander (test.EntityExpanderTest.BronKerboschExpanderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dev/shm/adapt/test/EntityExpanderTest.py", line 31, in testExpander
    parse_results = list(expander.expand(tags))
  File "/dev/shm/adapt/adapt/expander.py", line 160, in expand
    cliques = list(self._sub_expand(overlapping_spans))
  File "/dev/shm/adapt/adapt/expander.py", line 130, in _sub_expand
    for clique in get_cliques(entities.keys(), graph):
  File "/dev/shm/adapt/adapt/expander.py", line 47, in get_cliques
    for clique in bronk([], vertices, [], graph):
  File "/dev/shm/adapt/adapt/expander.py", line 35, in bronk
    for vertex in p[:]:
TypeError: 'dict_keys' object is not subscriptable

======================================================================
ERROR [0.001s]: test.IntentEngineTest (unittest.loader._FailedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib/python3.4/unittest/case.py", line 580, in run
    testMethod()
  File "/usr/lib/python3.4/unittest/loader.py", line 33, in testFailure
    raise self._exception
ImportError: Failed to import test module: test.IntentEngineTest
Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/loader.py", line 323, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.4/unittest/loader.py", line 301, in _get_module_from_name
    __import__(name)
  File "/dev/shm/adapt/test/IntentEngineTest.py", line 17
    except ValueError, e:
                     ^
SyntaxError: invalid syntax


======================================================================
ERROR [0.001s]: test_at_least_one (test.IntentTest.IntentTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dev/shm/adapt/test/IntentTest.py", line 44, in test_at_least_one
    for result in self.parser.parse("play the big bang theory"):
  File "/dev/shm/adapt/adapt/parser.py", line 38, in parse
    parse_results = bke.expand(tagged, clique_scoring_func=score_clique)
  File "/dev/shm/adapt/adapt/expander.py", line 169, in expand
    cliques = list(self._sub_expand(overlapping_spans))
  File "/dev/shm/adapt/adapt/expander.py", line 130, in _sub_expand
    for clique in get_cliques(entities.keys(), graph):
  File "/dev/shm/adapt/adapt/expander.py", line 47, in get_cliques
    for clique in bronk([], vertices, [], graph):
  File "/dev/shm/adapt/adapt/expander.py", line 35, in bronk
    for vertex in p[:]:
TypeError: 'dict_keys' object is not subscriptable

======================================================================
ERROR [0.001s]: test_basic_intent (test.IntentTest.IntentTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dev/shm/adapt/test/IntentTest.py", line 33, in test_basic_intent
    for result in self.parser.parse("play the big bang theory"):
  File "/dev/shm/adapt/adapt/parser.py", line 38, in parse
    parse_results = bke.expand(tagged, clique_scoring_func=score_clique)
  File "/dev/shm/adapt/adapt/expander.py", line 169, in expand
    cliques = list(self._sub_expand(overlapping_spans))
  File "/dev/shm/adapt/adapt/expander.py", line 130, in _sub_expand
    for clique in get_cliques(entities.keys(), graph):
  File "/dev/shm/adapt/adapt/expander.py", line 47, in get_cliques
    for clique in bronk([], vertices, [], graph):
  File "/dev/shm/adapt/adapt/expander.py", line 35, in bronk
    for vertex in p[:]:
TypeError: 'dict_keys' object is not subscriptable

======================================================================
ERROR [0.001s]: test_basic_intent_with_alternate_names (test.IntentTest.IntentTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dev/shm/adapt/test/IntentTest.py", line 61, in test_basic_intent_with_alternate_names
    for result in self.parser.parse("play the big bang theory"):
  File "/dev/shm/adapt/adapt/parser.py", line 38, in parse
    parse_results = bke.expand(tagged, clique_scoring_func=score_clique)
  File "/dev/shm/adapt/adapt/expander.py", line 169, in expand
    cliques = list(self._sub_expand(overlapping_spans))
  File "/dev/shm/adapt/adapt/expander.py", line 130, in _sub_expand
    for clique in get_cliques(entities.keys(), graph):
  File "/dev/shm/adapt/adapt/expander.py", line 47, in get_cliques
    for clique in bronk([], vertices, [], graph):
  File "/dev/shm/adapt/adapt/expander.py", line 35, in bronk
    for vertex in p[:]:
TypeError: 'dict_keys' object is not subscriptable

======================================================================
ERROR [0.002s]: test_intent_with_regex_entity (test.IntentTest.IntentTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dev/shm/adapt/test/IntentTest.py", line 78, in test_intent_with_regex_entity
    for result in self.parser.parse("the big bang theory"):
  File "/dev/shm/adapt/adapt/parser.py", line 38, in parse
    parse_results = bke.expand(tagged, clique_scoring_func=score_clique)
  File "/dev/shm/adapt/adapt/expander.py", line 169, in expand
    cliques = list(self._sub_expand(overlapping_spans))
  File "/dev/shm/adapt/adapt/expander.py", line 130, in _sub_expand
    for clique in get_cliques(entities.keys(), graph):
  File "/dev/shm/adapt/adapt/expander.py", line 47, in get_cliques
    for clique in bronk([], vertices, [], graph):
  File "/dev/shm/adapt/adapt/expander.py", line 35, in bronk
    for vertex in p[:]:
TypeError: 'dict_keys' object is not subscriptable

----------------------------------------------------------------------
Ran 22 tests in 0.014s

FAILED (errors=8)

Generating XML reports...
```

**Comment by clusterfudge** [comment]
That's a futures package replacement of dict? There's a lot of places in the code where dictionaries are implicitly declared (using the {...} syntax, as opposed to dict(...)). I'd like the code to be consistent, so that may actually be an involved change. Let me know what you think.

**Comment by ivuk** [comment]
Nah, I'll just try to cook up something that takes care of the differences in `.keys()` return types, hopefully without resorting to the "wrap it in a `list()` cast". :)

**Comment by ivuk** [comment]
Well, it seems  that [most](http://python-future.org/compatible_idioms.html#iterating-through-dict-keys-values-items) of the [available](http://legacy.python.org/dev/peps/pep-0469/) [methods](http://python-future.org/compatible_idioms.html#iterating-through-dict-keys-values-items) would make the existing code behave like Python 3, which makes it a bit more involved change, since more stuff needs to be checked. I've tried using the `future.utils` things such as `iterkeys`, but it seems to me that explicit casting to `list()` might be a decent enough alternative.

If casting the `dict.keys()` calls would be acceptable, in order to pass the tests, there's a single change that needs to be done (IIRC it was the `entities.keys()` call in `expander.py`; I could be wrong, though, since it was a while ago :)). In order to make the code more consistent, we could substitute the i.e. `for key in groups.keys():` and `for clique in get_cliques(entities.keys(), graph):` calls with `for key in list(groups):` and `for clique in get_cliques(list(entities), graph):`. Likewise for the remaining `dict.keys()` calls. There are [some potential issues](http://blog.labix.org/2008/06/27/watch-out-for-listdictkeys-in-python-3) with this approach, but as far as I can tell, it seems to be the "standard" method for doing this.

I've done some light testing of this approach with 2.7 and 3.4, and it seems it can run both the tests and examples.

The cleanest version of it would be something like `for elem in dictname`, but I haven't tested this enough, and I seem to remember that I've still had to cast it explicitly somewhere.

**Comment by clusterfudge** [comment]
I have to look more closely at the first (for key in groups.keys()), but the latter (clique in get_cliques) is definitely a non-starter. That's one of the chunks of code that is heavily short-circuited by using generators, and fully executing the generator would result in dramatically different performance characteristics.

**Comment by ivuk** [comment]
Ah, sorry, I think I didn't write it out clearly enough, it would go from this:
```diff
for key in groups.keys():
```
to this:
```
for key in list(groups): 
```
and from this:
```
for clique in get_cliques(entities.keys(), graph):
```
to this:
```
for clique in get_cliques(list(entities), graph):
```
I realize that performance could change drastically here, but in this case, it seems to me that these things are identical (or nearly identical), AFAIK the call to `entities.keys()` should return a new `list()` of keys, which shouldn't be that different than an explicit `list(entities)` call. I could be missing something, though. :)

**Comment by clusterfudge** [comment]
Got it, that's a much less scary change :). I'd be more than happy to review that, and I'll do some local perf tests (in both 2 and 3). I can't promise it'll get done today, but probably over the weekend. 

Awesome work here! I am learning things about the python, and that always makes me :smile:

**Comment by ivuk** [comment]
OK, I'll create a `py3-support` branch in my fork, and push the Python 3 changes that we've discussed here to it:
*  Remove the `wsgiref` package from `requirements.txt` and add `future`
*  Replace the `except ValueError, e:` with `except ValueError as e:`
*  Replace the `dict.keys()` calls with explicit casts to `list()`

If you agree, I'll ping you here when I'm done, so you can take a look and review the changes. Particularly the casting part, since I may have gone a bit overboard on that. It's a handful of changes, though, should be easy enough to review. :)

**Comment by clusterfudge** [comment]
Sounds good!

**Comment by ivuk** [comment]
[This](https://github.com/ivuk/adapt/tree/py3-support) should be it. Take a peek when you find the time, no rush. Hope you'll have a great weekend!

**Comment by clusterfudge** [comment]
Hey Igor, this looks pretty clean to me. Would you mind creating a pull request from your fork?

Thanks!

**Comment by ivuk** [comment]
Sure, do you want to merge this into `master` or another branch? So I know which to choose when opening the pull request.

**Comment by clusterfudge** [comment]
Master will be fine, we don't maintain another branch at this time.

**Comment by clusterfudge** [comment]
Also, if you can rebase off of master, I just enabled TravisCI, and I'd love to see if it will build your PR for us :smile:

**Comment by clusterfudge** [comment]
This issue is now resolved. Thanks, ivuk!
