### ISSUE TITLE
.voc files not using the `'` character

### ISSUE THREAD

**Issue by LongBoolean** [MycroftAI/adapt#20]
Keywords with a ' in them don't seem to work, they just say searching for...
The text detected from the voice has a '. Perhaps the voc file is stripping these out?

For example. if the keyword is "that's a spy" and I say that phrase, mycroft will say "searching for that's a spy" instead of activating the skill.

I don't know of coarse but one possibility is that whatever is reading in the voc file is changing it from "that's a spy" to "thats a spy" 
Or perhaps this is the desired behavior and I need to somehow escape the character?

**Comment by the-kid89** [comment]
can you provide a code example?

**Comment by LongBoolean** [comment]
"that's a spy" is a keyword for one of the intents in my tf2 skill. Other than that I don't see what other code example would be useful to you.

**Comment by hariedo** [comment]
Kind of an old entry, but please see https://mycroft.ai/documentation/skills/common-issues-in-skills-development/

Use "that is a spy" in your code, because the listener will convert "that's" to "that is" for you.

**Comment by clusterfudge** [comment]
Closing as resolved (and somewhat mycroft-core specific).
