### ISSUE TITLE
Allow "empty" regexes.

### ISSUE THREAD

**Issue by traverseda** [MycroftAI/adapt#29]
```
engine.register_regex_entity("on (?P<Task>.*)")
```

works, but

```
engine.register_regex_entity("(?P<Task>.*)")
```

results in

```

Traceback (most recent call last):
  File "/home/traverseda/bin/ti", line 518, in <module>
    for intent in engine.determine_intent(' '.join(sys.argv[1:])):
  File "/usr/lib/python3.5/site-packages/adapt/engine.py", line 57, in determine_intent
    for result in parser.parse(utterance, N=num_results):
  File "/usr/lib/python3.5/site-packages/adapt/parser.py", line 20, in parse
    tagged = self._tagger.tag(utterance.lower())
  File "/usr/lib/python3.5/site-packages/adapt/entity_tagger.py", line 87, in tag
    entities = self._sort_and_merge_tags(entities)
  File "/usr/lib/python3.5/site-packages/adapt/entity_tagger.py", line 32, in _sort_and_merge_tags
    decorated.sort()
TypeError: unorderable types: dict() < dict()

```

---

I presume that's intentional, I'm registering a regex instead of just handing it an function/regex-object. But it's still inconvenient.

**Comment by anselm94** [comment]
`engine.register_regex_entity` needs a **regular expression (regex) pattern** (The word _on_ followed by _Task_) to detect your required entity (entity is _Task_ in your case).
Without having a pattern, it's impossible to detect the entity unless you supply a dictionary of _Task_ s, as in [multi_intent_parser](https://github.com/MycroftAI/adapt/blob/master/examples/multi_intent_parser.py) example.

**Comment by clusterfudge** [comment]
@anselm94 isn't explicitly correct. It's possible to register a wildcard regex entity (effectively .*) for things like the message body of a tweet, but generally you're not going to like the result. 

@traverseda It looks like you're possibly injecting some objects into the engine that it's not expecting to be there. Can you provide more context on your code than the above? Best would be a PR with a failing unit test, and I can iterate on it until it passes. Thanks!

**Comment by traverseda** [comment]
@clusterfudge , I've got a failing example on pastebin [here](http://pastebin.com/yHRGq5vH). Being a web-dev, I haven't been exposed to test cases all that much. I'd rather not just drop that into the tests folder with test in the name, but it does cause a crash.

I'm hoping that wildcards will work for my goal, adding entirely new tasks.

**Comment by clusterfudge** [comment]
Unfortunately, the pastebin has expired and I'm not able to pick this up where I dropped it (4 years ago :( ). Marking as stale and scheduling to be closed on 9/17.
