### ISSUE TITLE
What would be needed for translation to Portuguese (pt-BR)?

### ISSUE THREAD

**Issue by tfontoura** [MycroftAI/adapt#61]
I'm not sure where to start from, or even if it is already available.

**Comment by Chekhov** [comment]
1. Does the NLP have Portuguese ?
2. Does the system accept that ? 

Probably what you'd do is translation of the voice or text to english and the system would deal with it. I guess our biggest problem then would be translating accurately.

**Comment by penrods** [comment]
Sorry this was left unanswered for so long.  Adapt should work fine with any language, it isn't English specific.  Mycroft-core successfully has used it in several already.
