### ISSUE TITLE
Context manager question.

### ISSUE THREAD

**Issue by jumper047** [MycroftAI/adapt#64]
__DISCLAIMER__
First of all, i am very bad in programming, so sorry, if my question is stupid. Just close and forget. 

I have an issue with context manager: i have an intent of a timer, with minute/second entities. So, when engine matches this intent and frames from previous match are still in context manager, he gets, for example, seconds from current phrase, and minutes from previous. So, is there an easy way to "blacklist" some entities?

**Comment by clusterfudge** [comment]
For a bit more context, can you tell me if you're using the context manager in your own code, or if this is within mycroft-core? If the former, can you share a gist?

**Comment by jumper047** [comment]
I use it in my own voice assistant. Gist is [here](https://gist.github.com/jumper047/1aca3508873d82199960986b5ff694d9).

**Comment by jumper047** [comment]
Oh, i understand how i can do what i want. So, my issue not an issue anymore:)
