### ISSUE TITLE
Why is confidence only 0.375 for the regex example?

### ISSUE THREAD

**Issue by remster85** [MycroftAI/adapt#72]
Hi guys, I like the framework a lot and plan to use it and contribute to it.
I was playing with the regex [example](https://github.com/MycroftAI/adapt/blob/master/examples/regex_intent_parser.py).
and executing the command, it returns a low confidence.

> python regex.py "what's the weather like in tokyo"

```
    "intent_type": "WeatherIntent",
    "WeatherKeyword": "weather",
    "Location": "tokyo",
    "target": null,
    "confidence": 0.375
```

**Comment by clusterfudge** [comment]
Matches from regular expressions are weighted lower than matches from vocabulary. You can see where this confidence rating is applied in [EntityTagger](https://github.com/MycroftAI/adapt/blob/master/adapt/entity_tagger.py#L68).

**Comment by remster85** [comment]
thank you for the explanation!
