### ISSUE TITLE
watchOS support

### ISSUE THREAD

**Issue by dyah10** [MycroftAI/adapt#78]
Hi,

We're trying to get intent parsing working on watchOS (version 4.0+) with audio as input. Is there somewhere/someone we can be pointed to to help us port Adapt or Padatious to iOS? Or are there plans in the road map to support iOS and watchOS?

**Comment by penrods** [comment]
If you'd like to give it a crack, we'd be happy to  accept contributions, but I'm afraid neither of those are on our near-term roadmap.
