### ISSUE TITLE
Releases not being tagged

### ISSUE THREAD

**Issue by nullr0ute** [MycroftAI/adapt#80]
Looking at the git logs there's been 0.3.1 and 0.3.2 releases but they've not been tagged in git, or at least the tags haven't been pushed to github.

**Comment by clusterfudge** [comment]
Hey @nullr0ute , it does look like we skipped a tag for [0.3.1](https://github.com/MycroftAI/adapt/commit/f96fa4c694f05c56c300627f6dd9cf86fb4b7559), but do appear to have one for [0.3.2](https://github.com/MycroftAI/adapt/releases/tag/release%2Fv0.3.2). 

@forslund would you mind pushing a tag please?

**Comment by forslund** [comment]
I've added the missing v0.3.1 release now.
