### ISSUE TITLE
tokenize voice input?

### ISSUE THREAD

**Issue by m3m3-chan** [MycroftAI/adapt#94]
Hello, 

Does the tokenizer work with  voice input too?  If yes, I would appreciate it if you can guide me to which file/function deals with that.
I'm running Win10 and want to run the code from my Conda Python env

Thanks,

**Comment by forslund** [comment]
Hi,

adapt is purely for parsing text, a STT step is needed to handle voice input.

**Comment by m3m3-chan** [comment]
thanks.
